name:                EmulsionGen
version:             0.1.0.0
github:              "aelkholy/EmulsionGen"
license:             OtherLicense
author:              "Alexander Elkholy"
maintainer:          "alexanderelkholy@gmail.com"
copyright:           "2019 Alexander Elkholy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aelkholy/EmulsionGen#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- mtl
- sbv
- optparse-applicative
- recursion-schemes

library:
  source-dirs: src

executables:
  EmulsionGen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EmulsionGen

tests:
  EmulsionGen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EmulsionGen
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-hunit